services:

  mysql_login:
    image: mysql:8.0
    container_name: mysql_login
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nico1415
      MYSQL_DATABASE: retrostore_login
      MYSQL_USER: retrostore
      MYSQL_PASSWORD: nico1415
    ports:
      - "3310:3306"
    volumes:
      - mysql_login_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

  mysql_autenticador:
    image: mysql:8.0
    container_name: mysql_autenticador
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nico1415
      MYSQL_DATABASE: retrostore_autenticador
      MYSQL_USER: retrostore
      MYSQL_PASSWORD: nico1415
    ports:
      - "3311:3306"
    volumes:
      - mysql_autenticador_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

          mysql_inventario:
    image: mysql:8.0
    container_name: mysql_inventario
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nico1415
      MYSQL_DATABASE: retrostore_inventario
      MYSQL_USER: retrostore
      MYSQL_PASSWORD: nico1415
    ports:
      - "3312:3306"
    volumes:
      - mysql_inventario_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  mysql_login_data:
  mysql_autenticador_data:
  mysql_inventario_data:
